project_id = "qnrrixfwicybhchvuutu"

[functions.shortlinks]
verify_jwt = false

[functions.generate-bio]
verify_jwt = false

[functions.qr]
verify_jwt = false

[functions.canva-connect]
verify_jwt = false
