import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.products': 'Products',
    'nav.products.linkInBio': 'Link in Bio',
    'nav.products.linkInBio.desc': 'Your entire brand in one link',
    'nav.products.linkShortener': 'Link Shortener',
    'nav.products.linkShortener.desc': 'Create trackable short URLs',
    'nav.products.qrGenerator': 'QR Generator',
    'nav.products.qrGenerator.desc': 'Generate QR codes for any link',
    'nav.templates': 'Templates',
    'nav.pricing': 'Pricing',
    'nav.features': 'Features',
    'nav.login': 'Log in',
    'nav.signup': 'Sign up free',
    
    // Hero
    'hero.badge': 'Link in bio, elevated',
    'hero.title1': 'One link.',
    'hero.title2': 'All of you.',
    'hero.title3': 'powerful link.',
    'hero.subtitle': 'The link in bio that looks like you hired a designer.',
    'hero.description': 'Bring your brand to life with stunning link-in-bio pages. Every connection is a journey, every click a new opportunity.',
    'hero.cta': 'Claim',
    'hero.cta2': 'See Examples',
    'hero.handlePlaceholder': 'yourname',
    'hero.stat1': 'Setup in 2 min',
    'hero.stat2': 'Built for Creators',
    'hero.mockup.name': 'TheCreator 🌺',
    'hero.mockup.bio': 'Content Creator & Entrepreneur ✨',
    'hero.mockup.btn1': 'Shop My Favorites',
    'hero.mockup.btn2': 'Join My Team',
    'hero.mockup.btn3': 'Free Starter Guide',
    'hero.mockup.clicks': '+127 clicks today',
    'hero.mockup.setup': '⚡ Setup in 2 min',
    'hero.noCreditCard': 'No card needed.',
    'hero.freeForever': 'Free to start.',
    'hero.phone.link1': 'Latest reels',
    'hero.phone.link1sub': '@maya.rivera',
    'hero.phone.link2': 'Shop my picks',
    'hero.phone.link2sub': 'New drop · 48h left',
    'hero.phone.link3': 'Listen now',
    'hero.phone.link3sub': 'Spotify · Apple Music',
    'hero.phone.link4': 'Book a session',
    'hero.phone.link4sub': '3 slots left this week',
    
    // Problem Section
    'problem.title': 'Sound',
    'problem.title2': 'familiar?',
    'problem.subtitle': 'Most creators struggle with the same frustrating problems',
    'problem.item1.title': 'Scattered links, lost sales',
    'problem.item1.desc': 'Your audience clicks away before they find what matters. Multiple links mean multiple chances to lose them.',
    'problem.item2.title': 'Hours wasted on setup',
    'problem.item2.desc': 'Building a website takes weeks. Updating it takes hours. Your content moves faster than your tools.',
    'problem.item3.title': "No idea what's working",
    'problem.item3.desc': "You're flying blind. Which links convert? Where do visitors drop off? Traditional bios tell you nothing.",
    
    // Solution Section
    'solution.title': 'Your bio link,',
    'solution.title2': 'elevated',
    'solution.description': 'TitiLinks transforms your single bio link into a dynamic, trackable storefront that converts followers into customers—in minutes, not months.',
    'solution.feature1': 'Beautiful, mobile-first design',
    'solution.feature2': 'Built-in analytics & tracking',
    'solution.feature3': 'Mode switching for different audiences',
    'solution.feature4': 'Lightning-fast load times',
    'solution.clicks': '+127 clicks today',
    'solution.mockup.name': 'TheCreator 🥰',
    'solution.mockup.bio': 'Welcome to my world ✨',
    
    // Features Section
    'features.title': 'Everything you need to',
    'features.title2': 'convert',
    'features.subtitle': 'Powerful features that help you turn clicks into customers',
    'features.themes.title': 'Stunning Themes',
    'features.themes.desc': 'Choose from beautiful presets or customize colors, fonts, and layouts to match your brand perfectly.',
    'features.analytics.title': 'Deep Analytics',
    'features.analytics.desc': 'Track every click, view, and conversion. Know exactly where your audience comes from and what they want.',
    'features.modes.title': 'Mode Switching',
    'features.modes.desc': 'Give visitors a second page with its own links and hero—they switch with one click.',
    'features.speed.title': 'Blazing Fast',
    'features.speed.desc': 'Sub-100ms load times. Your page loads before they can blink, so they never bounce.',
    'features.privacy.title': 'Privacy First',
    'features.privacy.desc': "Your data stays yours. We don't sell your analytics or share visitor information.",
    'features.builder.title': 'Manual or AI Builder',
    'features.builder.desc': 'Build your page your way—craft it manually with full control, or let AI create it for you in seconds.',
    
    // How It Works
    'how.title': 'Live in',
    'how.title2': '3 simple steps',
    'how.subtitle': 'From signup to sharing in under 5 minutes',
    'how.step1.title': 'Sign up in seconds',
    'how.step1.desc': 'Create your account with email or Google. No credit card required to get started.',
    'how.step2.title': 'Customize your page',
    'how.step2.desc': 'Add your links, products, and media. Pick a theme that matches your vibe.',
    'how.step3.title': 'Share & grow',
    'how.step3.desc': 'Drop your link in your bio and watch the analytics roll in. Optimize and convert.',
    
    // Testimonials
    'testimonials.title': 'Loved by',
    'testimonials.title2': 'creators',
    'testimonials.subtitle': "Join thousands of creators who've upgraded their bio link",
    
    // Stats
    'stats.title': 'Results that',
    'stats.title2': 'speak',
    'stats.subtitle': 'Real numbers from real creators',
    'stats.ctr': 'Higher CTR',
    'stats.ctr.desc': 'vs. traditional bio links',
    'stats.conversions': 'More Conversions',
    'stats.conversions.desc': 'with mode switching',
    'stats.load': 'Avg Load Time',
    'stats.load.desc': 'globally distributed',
    
    // Pricing
    'pricing.title': 'Simple,',
    'pricing.title2': 'transparent',
    'pricing.title3': 'pricing',
    'pricing.subtitle': 'Start free and scale as you grow. No hidden fees.',
    'pricing.monthly': 'Monthly',
    'pricing.annual': 'Annual',
    'pricing.save': 'Save up to 40%',
    'pricing.period.monthly': '/month',
    'pricing.period.annual': '/mo, billed annually',
    'pricing.free': 'Free',
    'pricing.free.period': 'forever',
    'pricing.free.desc': 'Perfect for getting started',
    'pricing.pro': 'Pro',
    'pricing.pro.desc': 'For serious creators',
    'pricing.premium': 'Premium',
    'pricing.premium.desc': 'For teams & agencies',
    'pricing.popular': 'Most Popular',
    'pricing.cta.free': 'Start Free',
    'pricing.cta.pro': 'Go Pro',
    'pricing.cta.premium': 'Contact Sales',
    'pricing.comingSoon': 'Coming Soon',
    
    // CTA
    'cta.badge': 'Start free today',
    'cta.title': 'Ready to',
    'cta.title2': 'level up',
    'cta.title3': 'your bio?',
    'cta.description': "Join thousands of creators who've already made the switch. Your new link-in-bio is just a click away.",
    'cta.button': 'Start Free Today',
    'cta.button2': 'Watch Demo',
    'cta.note': 'No credit card required · Free forever tier · Setup in 2 minutes',
    
    // Footer
    'footer.tagline': 'The link-in-bio for creators who sell. Turn clicks into customers.',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.copyright': 'All rights reserved.',
    'footer.made': 'Made with ✨ for creators everywhere',

    // Onboarding Flow
    'onboardingFlow.stepStyle': 'Style',
    'onboardingFlow.stepProfile': 'Profile',
    'onboardingFlow.stepLayout': 'Layout',
    'onboardingFlow.stepVibe': 'Vibe',
    'onboardingFlow.stepLinks': 'Links',
    'onboardingFlow.stepLive': 'Live',
    'onboardingFlow.chooseStyle': 'Choose Your Style',
    'onboardingFlow.chooseStyleDesc': 'Pick a layout that matches your brand.',
    'onboardingFlow.styleClassic': 'Classic',
    'onboardingFlow.styleClassicDesc': 'Clean centered layout with rounded avatar and stacked links.',
    'onboardingFlow.styleHero': 'Hero',
    'onboardingFlow.styleHeroDesc': 'Photo fills the top half, links below.',
    'onboardingFlow.styleFullBleed': 'Full Screen',
    'onboardingFlow.styleFullBleedDesc': 'Your photo fills the whole page.',
    'onboardingFlow.continue': 'Continue',
    'onboardingFlow.back': 'Back',
    'onboardingFlow.skipForNow': 'Skip for now',
    'onboardingFlow.yourProfile': 'Your Profile',
    'onboardingFlow.yourProfileDesc': 'Tell us a bit about yourself.',
    'onboardingFlow.displayName': 'Display Name',
    'onboardingFlow.displayNamePlaceholder': 'Your Name',
    'onboardingFlow.username': 'Username',
    'onboardingFlow.usernamePlaceholder': 'yourname',
    'onboardingFlow.uploadPhoto': 'Upload photo',
    'onboardingFlow.changePhoto': 'Change photo',
    'onboardingFlow.photoNudgeTitle': 'Add a photo?',
    'onboardingFlow.photoNudgeBodyHero': 'Your page looks best with a photo. Want to add one now?',
    'onboardingFlow.photoNudgeBodyFullBleed': 'Your full-bleed page is built around a background photo. Want to add one now?',
    'onboardingFlow.photoNudgeAdd': 'Add photo',
    'onboardingFlow.photoNudgeNotNow': 'Not now',
    'onboardingFlow.photoSkipTitle': 'No photo — no problem',
    'onboardingFlow.photoSkipBody': 'You can add one anytime from Edit Profile in your dashboard.',
    'onboardingFlow.photoSkipContinue': 'Got it, continue',
    'onboardingFlow.stepButtons': 'Buttons',
    'onboardingFlow.chooseButtons': 'Choose Your Buttons',
    'onboardingFlow.chooseButtonsDesc': 'Pick the button style for your page. Previewed on your photo.',
    'onboardingFlow.accentColor': 'Accent color',
    'onboardingFlow.buttonSizeLarge': 'Large',
    'onboardingFlow.buttonSizeSmall': 'Small',
    'onboardingFlow.buttonShape': 'Button shape',
    'onboardingFlow.pickVibe': 'Pick Your Vibe',
    'onboardingFlow.pickVibeDesc': 'Customize the look and feel of your page.',
    'onboardingFlow.background': 'Background',
    'onboardingFlow.buttonStyle': 'Button Style',
    'onboardingFlow.fontChoice': 'Font',
    'onboardingFlow.socialPlatforms': 'Social Platforms',
    'onboardingFlow.addLinks': 'Add Your Links',
    'onboardingFlow.addLinksDesc': 'Paste your social media URLs below.',
    'onboardingFlow.noSocialsSelected': 'Go back to select your social platforms first.',
    'onboardingFlow.yourSocialPlatforms': 'Your Social Platforms',
    'onboardingFlow.yourSocialPlatformsDesc': "Tap to add the platforms you're on. You'll add your links in the editor.",
    'onboardingFlow.youreLive': "You're Live!",
    'onboardingFlow.youreLiveDesc': 'Your page is ready to share with the world.',
    'onboardingFlow.shareLink': 'Share my link',
    'onboardingFlow.goToDashboard': 'Go to my dashboard',
    'onboardingFlow.saveFailed': 'Failed to save. Please try again.',
    'onboardingFlow.usernameTaken': 'This username is already taken.',


    // Design Editor
    'design.title': 'Design Settings',
    'design.save': 'Save',
    'design.designTools': 'Design Tools',
    'design.pageStyle': 'Page Style',
    'design.pageStyleDesc': 'Choose how your profile looks to visitors',
    'design.styleClassic': 'Classic',
    'design.styleClassicDesc': 'Circle avatar, centered',
    'design.styleHero': 'Hero',
    'design.styleHeroDesc': 'Full-width photo overlay',
    'design.styleFullBleed': 'Full Screen',
    'design.styleFullBleedDesc': 'Immersive full-screen',
    'design.templateGallery': 'Template Gallery',
    'design.browseTemplates': 'Browse templates',
    'design.canvaStudio': 'Canva Studio',
    'design.comingSoon': 'Coming Soon',
    'design.checking': 'Checking...',
    'design.importDesigns': 'Import designs',
    'design.connectToImport': 'Connect to import',
    'design.canvaSetupHelp': 'Canva Setup Help - Click to expand',
    'design.canvaSetupIntro': 'Connect Canva to design custom headers and wallpapers:',
    'design.canvaStep1Prefix': 'In',
    'design.canvaStep1Create': 'create a',
    'design.canvaConnect': 'Canva Connect',
    'design.canvaStep1Suffix': 'integration',
    'design.canvaStep2': 'Add redirect URL:',
    'design.canvaStep3': 'Enable scopes:',
    'design.canvaStep3And': 'and',
    'design.canvaStep4Copy': 'Copy',
    'design.canvaClientId': 'Client ID',
    'design.canvaClientSecret': 'Client Secret',
    'design.canvaStep4Suffix': 'into environment variables',
    'design.canvaNote': 'Use "Your integrations" not "Your apps" in Canva.',
    'design.noteLabel': 'Note:',
    'design.mfaRequired': 'MFA Required',
    'design.mfaDesc': 'Enable MFA in Canva Settings \u2192 Login, then retry.',
    'design.retry': 'Retry',
    'design.canvaImports': 'Canva Imports',
    'design.disconnect': 'Disconnect',
    'design.background': 'Background',
    'design.header': 'Header',
    'design.replace': 'Replace',
    'design.remove': 'Remove',
    'design.headerLayout': 'Header Layout',
    'design.layoutOverlay': 'Overlay',
    'design.layoutOverlayDesc': 'Text on image',
    'design.layoutCard': 'Card',
    'design.layoutCardDesc': 'Image in card',
    'design.layoutSplit': 'Split',
    'design.layoutSplitDesc': 'Storefront style',
    'design.layoutCinematic': 'Cinematic',
    'design.layoutCinematicDesc': 'Full hero photo',
    'design.layoutImmersive': 'Immersive',
    'design.layoutImmersiveDesc': 'Full screen photo bg',
    'design.onlineIndicator': 'Online Indicator',
    'design.lastImportedCanva': 'Last imported from Canva',
    'design.importAnother': 'Import another design',
    'design.addAnotherCanva': 'Add another Canva design',
    'design.chooseCanvaDesign': 'Choose a Canva design',
    'design.canvaErrorMfa': 'MFA Required',
    'design.canvaErrorMfaDesc': 'Your Canva account requires Multi-Factor Authentication.',
    'design.canvaErrorPermission': 'Permission Required',
    'design.canvaErrorPermissionDesc': 'Design creation requires additional permissions.',
    'design.reconnectCanva': 'Reconnect Canva',
    'design.canvaErrorGeneric': 'Error',
    'design.canvaErrorGenericDesc': 'Something went wrong. Please try again.',
    'design.dismiss': 'Dismiss',
    'design.quickStartPresets': 'Templates',
    'design.mySavedPresets': 'My Saved Presets',
    'design.saveCurrent': 'Save Current',
    'design.saveThemePreset': 'Save Theme Preset',
    'design.saveThemePresetDesc': 'Save your current theme settings as a reusable preset.',
    'design.presetName': 'Preset Name',
    'design.presetPlaceholder': 'e.g., My Brand Theme',
    'design.cancel': 'Cancel',
    'design.savePreset': 'Save Preset',
    'design.noPresetsYet': 'No saved presets yet. Customize your theme and save it!',
    'design.microinteractions': 'Microinteractions',
    'design.microinteractionsDesc': 'Hover lift & press animations',
    'design.microinteractionsNote': 'Users with "reduce motion" enabled in their device settings will not see animations regardless of this setting.',
    'design.matchStyles': 'Match styles to background',
    'design.matchStylesDesc': 'Auto-adjust colors for readability',
    'design.matchStylesNote': 'When enabled, automatically adjusts overlay opacity and text color for better readability on image backgrounds.',
    'design.tabBackground': 'Background',
    'design.tabButtons': 'Buttons',
    'design.tabTypography': 'Typography',
    'design.tabTitle': 'Title',
    'design.tabFont': 'Font',
    'design.backgroundColor': 'Background Color',
    'design.mainTextColor': 'Main Text Color',
    'design.chooseFont': 'Choose Font',
    'design.update': 'Update',
    'design.resetToDefault': 'Reset to Default',
    'design.eyedropper': 'Pick color from screen',
    'design.backgroundType': 'Background Type',
    'design.solidColor': 'Solid Color',
    'design.gradient': 'Gradient',
    'design.image': 'Image',
    'design.choosePresetGradient': 'Choose a Preset Gradient',
    'design.backgroundImage': 'Background Image',
    'design.uploading': 'Uploading...',
    'design.uploadImage': 'Upload Image',
    'design.uploadNote': 'Max 5MB. Supported: JPEG, PNG, GIF, WebP',
    'design.overlaySettings': 'Overlay Settings',
    'design.overlayColor': 'Overlay Color',
    'design.overlayOpacity': 'Overlay Opacity:',
    'design.preview': 'Preview',
    'design.yourContentHere': 'Your content here',
    'design.buttonShape': 'Button Shape',
    'design.pill': 'Pill',
    'design.rounded': 'Rounded',
    'design.square': 'Square',
    'design.fillColor': 'Fill Color',
    'design.textColor': 'Text Color',
    'design.enableBorder': 'Enable Border',
    'design.borderColor': 'Border Color',
    'design.enableShadow': 'Enable Shadow',
    'design.density': 'Density',
    'design.compact': 'Compact',
    'design.normal': 'Normal',
    'design.roomy': 'Roomy',
    'design.sampleButton': 'Sample Button',
    'design.fontFamily': 'Font Family',
    'design.systemDefault': 'System Default',
    'design.serif': 'Serif',
    'design.monospace': 'Monospace',
    'design.sampleHeading': 'Sample Heading',
    'design.sampleText': 'This is how your text will appear on your page.',
    'design.livePreview': 'Live Preview',
    'design.designSaved': 'Design saved!',
    'design.designSaveFailed': 'Failed to save design',
    'design.presetSaved': 'Preset saved!',
    'design.presetSaveFailed': 'Failed to save preset',
    'design.presetDeleted': 'Preset deleted',
    'design.presetDeleteFailed': 'Failed to delete preset',
    'design.canvaConnected': 'Canva connected successfully!',
    'design.canvaConnectFailed': 'Failed to connect Canva',
    'design.canvaDisconnected': 'Canva disconnected',
    'design.canvaDisconnectFailed': 'Failed to disconnect Canva',
    'design.canvaNoAuthUrl': 'No authorization URL received',
    'design.canvaConnectInitFailed': 'Failed to initiate Canva connection',
    'design.canvaCreateFailed': 'Failed to create design in Canva',
    'design.canvaDesignUrlFailed': 'Failed to get design URL from Canva',
    'design.canvaOpeningEditor': 'Opening Canva editor...',
    'design.imgSizeError': 'Image must be 5MB or less',
    'design.imgTypeError': 'Only JPEG, PNG, GIF, and WebP images are allowed',
    'design.bgImageUploaded': 'Background image uploaded!',
    'design.bgUploadFailed': 'Failed to upload image',
    'design.timeJustNow': 'Just now',
    'design.timeMinsAgo': 'm ago',
    'design.timeHoursAgo': 'h ago',
    'design.timeDaysAgo': 'd ago',
    'design.gradientMidnight': 'Midnight',
    'design.gradientSunset': 'Sunset',
    'design.gradientOcean': 'Ocean',
    'design.canvaDeveloperPortal': 'Canva Developer Portal',

    // Editor Child Components (GoalsPanel, LinkTools, BlockList)
    'goals.title': 'Goals',
    'goals.primaryOffer': 'Primary Offer Goal',
    'goals.page2Goal': 'Page 2 Goal',
    'goals.selectItem': 'Select a link item',
    'goals.noGoalSet': 'No goal set',
    'goals.trackPrimary': 'Track clicks to your primary sales offer.',
    'goals.trackPage2': 'Track clicks to your Page 2 primary link.',
    'goals.addItemsFirst': 'Add some link items first to set goals.',
    'goals.save': 'Save Goals',
    'goals.saved': 'Goals saved',
    'goals.saveFailed': 'Failed to save goals',
    'goals.loadFailed': 'Failed to load items',
    'linkTools.createShortLink': 'Create Short Link',
    'linkTools.shortLinkCreated': 'Short link created',
    'linkTools.shortLinkReady': 'Your short link is ready',
    'linkTools.copied': 'Copied',
    'linkTools.copiedDesc': 'Short URL copied to clipboard',
    'linkTools.copyFailed': 'Failed to copy to clipboard',
    'linkTools.downloaded': 'Downloaded',
    'linkTools.downloadFailed': 'Failed to download QR code',
    'linkTools.downloadPng': 'Download PNG',
    'linkTools.downloadSvg': 'Download SVG',
    'linkTools.error': 'Error',
    'linkTools.loginRequired': 'You must be logged in to create short links',
    'blocks.loadFailed': 'Failed to load blocks',
    'blocks.orderUpdated': 'Block order updated',
    'blocks.orderFailed': 'Failed to update block order',
    'blocks.enabled': 'Block enabled',
    'blocks.disabled': 'Block disabled',
    'blocks.toggleFailed': 'Failed to update block',
    'blocks.primary_cta.title': 'Primary CTA',
    'blocks.primary_cta.subtitle': 'Your main call-to-action button',
    'blocks.product_cards.title': 'Products',
    'blocks.product_cards.subtitle': 'Showcase your products',
    'blocks.featured_media.title': 'Featured Media',
    'blocks.featured_media.subtitle': 'Photos and video links',
    'blocks.video_feed.title': 'Video Feeds',
    'blocks.video_feed.subtitle': 'Your latest videos, auto-updating',
    'blocks.text.title': 'Text',
    'blocks.text.subtitle': 'Add a heading and a paragraph',
    'blockEditor.heading': 'Heading (optional)',
    'blockEditor.headingPlaceholder': 'e.g. My Courses',
    'blockEditor.text': 'Text',
    'blockEditor.textPlaceholder': 'Write your paragraph...',
    'blockEditor.bio': 'Bio',
    'blockEditor.bioPlaceholder': 'Write something about yourself...',
    'blockEditor.styling': 'Styling:',
    'blockEditor.headingTab': 'Heading',
    'blockEditor.textTab': 'Text',
    'blockEditor.font': 'Font',
    'blockEditor.defaultFont': 'Default (page font)',
    'blockEditor.weight': 'Weight',
    'blockEditor.bold': 'Bold',
    'blockEditor.size': 'Size',
    'blockEditor.small': 'Small',
    'blockEditor.medium': 'Medium',
    'blockEditor.large': 'Large',
    'blockEditor.alignment': 'Alignment',
    'blockEditor.left': 'Left',
    'blockEditor.center': 'Center',
    'blockEditor.right': 'Right',
    'blockEditor.cancel': 'Cancel',
    'blockEditor.save': 'Save',
    'blockEditor.textSaved': 'Text saved',
    'blockEditor.textLoadError': 'Failed to load text',
    'blockEditor.textSaveError': 'Failed to save text',
    'blockEditor.bioSaved': 'Bio saved',
    'blockEditor.bioLoadError': 'Failed to load bio',
    'blockEditor.bioSaveError': 'Failed to save bio',
    'blocks.social_links.title': 'Social Platforms',
    'blocks.social_links.subtitle': 'Add your social platforms',
    'blocks.links.title': 'Featured Links',
    'blocks.links.subtitle': 'Add link',
    'blocks.email_subscribe.title': 'Email Capture',
    'blocks.email_subscribe.subtitle': 'Collect visitor emails',
    'blocks.social_icon_row.title': 'Social Icons',
    'blocks.social_icon_row.subtitle': 'Row of social media icons',
    'blocks.hero_card.title': 'Hero Card',
    'blocks.hero_card.subtitle': 'Profile hero section',
    'blocks.content_section.title': 'Content Section',
    'blocks.content_section.subtitle': 'Text and content block',
    'blocks.gallery.title': 'Gallery',
    'blocks.gallery.subtitle': 'Photo gallery',
    'blocks.carousel.title': 'Carousel',
    'blocks.carousel.subtitle': 'Swipeable row of link cards',
    'blocks.bio.title': 'Bio',
    'blocks.bio.subtitle': 'Tell visitors about yourself',

    // Gallery & shared block strings
    'gallery.label': 'Gallery',
    'gallery.photo': 'photo',
    'gallery.photos': 'photos',
    'gallery.uploadFailed': 'Failed to upload photo',
    'emptyState.noContent': 'No content yet',
    'emailSubscribe.defaultTitle': 'Stay up to date',
    'emailSubscribe.defaultPlaceholder': 'your@email.com',
    'emailSubscribe.defaultButton': 'Subscribe',
    'emailSubscribe.defaultSuccess': 'Thanks for subscribing!',
    'emailSubscribe.defaultName': 'Your name',
    'emailSubscribe.errorUnable': 'Unable to subscribe',
    'emailSubscribe.errorInvalidEmail': 'Please enter a valid email',
    'emailSubscribe.errorGeneric': 'Failed to subscribe',
    'emailSubscribe.errorRetry': 'Failed to subscribe. Please try again.',
    'contentSection.viewAll': 'View all',
    'editor.changePhotoToast': 'Go to Settings to change your profile photo',

    // Default block content (placeholders created during onboarding)
    'content.shopMyCollection': 'Shop My Collection',
    'content.newArrivalsEveryWeek': 'New arrivals every week',
    'content.myWebsite': 'My Website',
    'content.checkOutMyWebsite': 'Check out my website',
    'content.latestBlogPost': 'Latest Blog Post',
    'content.readMyLatestContent': 'Read my latest content',
    'content.workWithMe': 'Work With Me',
    'content.collaborationsPartnerships': 'Collaborations & partnerships',
    'content.productOne': 'Product One',
    'content.yourBestSeller': 'Your best seller',
    'content.productTwo': 'Product Two',
    'content.newArrival': 'New arrival',
    'content.productThree': 'Product Three',
    'content.fanFavorite': 'Fan favorite',
    'content.bookConsultation': 'Book a Consultation',
    'content.letsWorkTogether': "Let's work together",
    'content.myShowreel': 'My Showreel',
    'content.watchMyLatestWork': 'Watch my latest work',
    'content.portfolio': 'Portfolio',
    'content.viewMyFullPortfolio': 'View my full portfolio',
    'content.myResume': 'My Resume',
    'content.downloadMyCv': 'Download my CV',
    'content.pressKit': 'Press Kit',
    'content.mediaResources': 'Media resources',
    'content.testimonials': 'Testimonials',
    'content.whatClientsSay': 'What clients say',
    'content.followMeOnTiktok': 'Follow me on TikTok',
    'content.followMeOnInstagram': 'Follow me on Instagram',
    'content.subscribeToMyChannel': 'Subscribe to my channel',
    'content.connectProfessionally': 'Connect professionally',
    'content.followMyContent': 'Follow my content',
    'content.stayUpToDate': 'Stay up to date',
    'content.thanksForSubscribing': 'Thanks for subscribing!',
    'content.subscribe': 'Subscribe',
    'content.shopMyFavorites': 'Shop My Favorites',
    'content.exclusiveDeals': 'Exclusive deals just for you',
    'content.becomeACreator': 'Become a Creator',
    'content.joinAffiliateProgram': 'Join my affiliate program',
    'content.shopMyGamingGear': 'Shop My Gaming Gear',
    'content.theExactSetup': 'The exact setup I use',
    'content.joinMyAffiliateProgram': 'Join My Affiliate Program',
    'content.earnWhileYouGame': 'Earn while you game',
    'content.shopMySupplements': 'Shop My Supplements',
    'content.whatIUseDaily': 'What I use daily',
    'content.joinMyCoachingTeam': 'Join My Coaching Team',
    'content.buildYourFitnessBusiness': 'Build your fitness business',
    'content.streamMyMusic': 'Stream My Music',
    'content.availableOnAllPlatforms': 'Available on all platforms',
    'content.bookingCollaborations': 'Booking & collaborations',
    'content.shopMyRecommendations': 'Shop My Recommendations',
    'content.curatedForYou': 'Curated just for you',
    'content.joinMyTeam': 'Join My Team',
    'content.learnToEarnOnline': 'Learn to earn online',
    'content.subscribeNow': 'Subscribe Now',
    'content.unlockPremiumContent': 'Unlock premium content',
    'content.startCreating': 'Start Creating',
    'content.joinReferralProgram': 'Join my referral program',
    'content.featuredContent1': 'Featured Content 1',
    'content.featuredContent2': 'Featured Content 2',
    'content.featuredContent3': 'Featured Content 3',
    'content.primaryCta': 'Primary CTA',
    'content.products': 'Products',
    'content.socialLinks': 'Social Links',
    'content.links': 'Links',
    'content.featuredMedia': 'Featured Media',

    // Editor Page
    'editor.title': 'Link Editor',
    'editor.editing': 'Editing',
    'editor.viewPage': 'View Page',
    'editor.content': 'Content',
    'editor.design': 'Design',
    'editor.pages': 'Pages',
    'editor.page1Label': 'Page 1 Label',
    'editor.page2Label': 'Page 2 Label',
    'editor.page1': 'Page 1',
    'editor.page2': 'Page 2',
    'editor.configureFirst': 'Configure content for your first page.',
    'editor.configureSecond': 'Configure content for your second page.',
    'editor.stickyCta': 'Sticky CTA',
    'editor.stickyCtaDesc': 'Show floating CTA after scroll',
    'editor.blocks': 'Blocks',
    'editor.suggestLinks': 'Suggest Links',
    'editor.noMode': 'No mode found. Please refresh the page.',
    'editor.shareLinks': 'Share Links',
    'editor.defaultLink': 'Default Link',
    'editor.defaultLinkDesc': 'Default link that can auto-detect which page to show.',
    'editor.forcePage2': 'Forces Page 2 regardless of referrer.',
    'editor.linkTools': 'Link Tools',
    'editor.link': 'Link',
    'editor.refreshPreview': 'Refresh Preview',
    'editor.labelUpdated': 'Page label updated',
    'editor.labelFailed': 'Failed to update label',
    'editor.copied': 'Copied to clipboard!',
    'editor.copyFailed': 'Failed to copy',
    'editor.stickyEnabled': 'Sticky CTA enabled',
    'editor.stickyDisabled': 'Sticky CTA disabled',
    'editor.settingFailed': 'Failed to update setting',
    'editor.loadFailed': 'Failed to load page data',
    'editor.viewLive': 'View Live',
    'editor.addContent': 'Add Content',
    'editor.changePhoto': 'Change Profile Picture',
    'editor.previewPhoto': 'Preview Photo',
    'editor.savePhoto': 'Save Photo',
    'editor.cancel': 'Cancel',
    'editor.editPhoto': 'Edit Photo',
    'editor.chooseEditMethod': 'How would you like to edit your photo?',
    'editor.editManually': 'Edit Manually',
    'editor.aiAutoCrop': 'AI Auto Crop',
    'editor.cropImage': 'Crop Image',
    'editor.choosePage2Photo': 'Choose a photo for Page 2',
    'editor.uploadPhoto': 'Upload Photo',
    'editor.editCurrentPhoto': 'Edit current photo',
    'editor.newPhoto': 'New photo',
    'editor.useAiCrop': 'Use AI Crop',
    'editor.useOriginal': 'Use Original',
    'editor.aiAnalyzing': 'AI is analyzing your photo...',
    'editor.aiCropFailed': 'AI crop failed, try manual edit',
    'editor.dragToPosition': 'Drag to reposition',
    'editor.done': 'Done',
    'editor.editSocial': 'Edit Social Links',
    'editor.blocksLabel': 'Blocks',
    'editor.failedToggle': 'Failed to update block',
    'editor.failedReorder': 'Failed to reorder blocks',
    'editor.linkRemoved': 'Link removed',
    'editor.failedDelete': 'Failed to delete link',
    'editor.nameHandleCard': 'Name & Handle',
    'editor.socialIconsCard': 'Social Icons',
    'editor.nameSize': 'Name Size',
    'editor.handleSize': 'Handle Size',
    'editor.nameColor': 'Name Color',
    'editor.handleColor': 'Handle Color',
    'editor.padding': 'Padding',
    'editor.iconSize': 'Icon Size',
    'editor.nameHandleGap': 'Text Gap',

    // Profile Dashboard
    'dashboard.addContent': 'Add Content',
    'dashboard.myLinks': 'My Links',
    'dashboard.managePlatforms': 'Manage Platforms',
    'dashboard.managePlatformsDesc': 'Add or edit platform links',
    'dashboard.featuredLinks': 'Featured Links',
    'dashboard.featuredLinksDesc': 'Add link',
    'dashboard.primaryCta': 'Primary CTA',
    'dashboard.primaryCtaDesc': 'Your main call-to-action button',
    'dashboard.appearance': 'Appearance',
    'dashboard.addHeader': 'Add a Header',
    'dashboard.addHeaderDesc': 'Add custom titles above your links',
    'dashboard.profileCustomization': 'Profile Customization',
    'dashboard.profileCustomizationDesc': 'Choose fonts, background and text colors',
    'dashboard.videoProfile': 'Video Profile',
    'dashboard.videoProfileDesc': 'Add video to your profile image',
    'dashboard.nameEffects': 'Name & Handle',
    'dashboard.nameEffectsDesc': 'Add a shadow or outline so your name stays readable',
    'dashboard.pages': 'Pages',
    'dashboard.pagesDesc': 'Add a second page visitors can switch to',
    'dashboard.videoFeeds': 'Video Feeds',
    'dashboard.videoFeedsDesc': 'Show your latest YouTube videos (Instagram and TikTok soon)',
    'dashboard.ecommerce': 'E-Commerce',
    'dashboard.newMerch': 'New Merch',
    'dashboard.newMerchDesc': 'Add merch',
    'dashboard.products': 'Products',
    'dashboard.digitalProducts': 'Digital Products',
    'dashboard.digitalProductsDesc': 'Manage Digital Products',
    'dashboard.lockedProducts': 'Locked Products',
    'dashboard.lockedProductsDesc': 'Manage Locked Products',
    'dashboard.events': 'Events',
    'dashboard.createEvent': 'Create Custom Event',
    'dashboard.createEventDesc': 'Add custom event',
    'dashboard.forms': 'Forms',
    'dashboard.createForm': 'Create Form',
    'dashboard.createFormDesc': 'Add custom form',
    'dashboard.analytics': 'Analytics',
    'dashboard.trackingPixels': 'Tracking Pixels',
    'dashboard.trackingPixelsDesc': 'Add Meta, TikTok, or GA tags',
    'dashboard.comingSoon': 'Coming soon!',
    'dashboard.openDesignTab': 'Open the Design tab',
    'dashboard.templateGallery': 'Template Gallery',
    'dashboard.templateGalleryDesc': 'Browse and apply page templates',
    'dashboard.noMode': 'No mode found',
    'dashboard.blockNotCreated': "This block hasn't been created yet.",
    'dashboard.failedOpen': 'Failed to open editor',

    // Analytics Page
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Track your page performance',
    'analytics.views7d': 'Views (7d)',
    'analytics.clicks7d': 'Clicks (7d)',
    'analytics.last30d': 'last 30d',
    'analytics.clicks': 'clicks',
    'analytics.goalPerformance': 'Goal Performance',
    'analytics.primaryOfferGoal': 'Primary Offer Goal',
    'analytics.goal': 'Goal',
    'analytics.setGoals': 'Set Goals',
    'analytics.setGoalsDesc': 'Set goals to track conversion performance',
    'analytics.notSet': 'Not set',
    'analytics.topDestinations': 'Top Destinations',
    'analytics.noClicks': 'No outbound clicks recorded yet',
    'analytics.trafficSources': 'Traffic Sources',
    'analytics.otherDirect': 'Other / Direct',
    'analytics.noTraffic': 'No traffic data yet',
    'analytics.modeDistribution': 'Mode Distribution',
    'analytics.noViews': 'No page views recorded yet',
    'analytics.ofTraffic': 'of traffic',
    'analytics.views': 'views',
    'analytics.ctr': 'CTR',
    'analytics.shortLinks': 'Short Links',
    'analytics.totalClicks': 'Total clicks:',
    'analytics.code': 'Code',
    'analytics.destination': 'Destination',
    'analytics.lastClick': 'Last Click',
    'analytics.noShortLinks': 'No short links created yet',

    // Settings Page
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account preferences',
    'settings.languageTitle': 'Language / Idioma',
    'settings.languageDesc': 'Choose your preferred language for the app interface',
    'settings.languageEn': 'English',
    'settings.languageEs': 'Español',
    'settings.switchToEs': 'Switch to Spanish / Cambiar a Español',
    'settings.switchToEn': 'Cambiar a Inglés / Switch to English',
    'settings.appearanceTitle': 'Appearance',
    'settings.appearanceDesc': 'Choose between light and dark mode',
    'settings.darkMode': 'Dark mode',
    'settings.lightMode': 'Light mode',
    'settings.themeToggleDesc': 'Toggle between light and dark appearance',
    'settings.notificationsTitle': 'Notifications',
    'settings.notificationsDesc': 'Manage how you receive updates and alerts',
    'settings.emailNotifications': 'Email notifications',
    'settings.emailNotificationsDesc': 'Receive updates about your page performance',
    'settings.weeklyDigest': 'Weekly digest',
    'settings.weeklyDigestDesc': 'Get a summary of your analytics every week',

    // Dashboard Page
    'dash.title': 'Dashboard',
    'dash.welcome': 'Welcome to your TitiLinks dashboard',
    'dash.last7days': 'Last 7 days',
    'dash.allTime': 'All time',
    'dash.totalViews': 'Total Views',
    'dash.linkClicks': 'Link Clicks',
    'dash.clickRate': 'Click Rate',
    'dash.activeLinks': 'Active Links',
    'dash.periodLast7': 'last 7 days',
    'dash.periodLast30': 'last 30 days',
    'dash.quickStart': 'Quick Start',
    'dash.quickStartDesc': 'Get started by setting up your profile in the Setup tab, then add your links in the Editor.',

    // Dashboard Layout
    'dashLayout.dashboard': 'Dashboard',
    'dashLayout.editor': 'Editor',
    'dashLayout.design': 'Customize Profile',
    'dashLayout.analytics': 'Analytics',
    'dashLayout.settings': 'Settings',
    'dashLayout.profileSetup': 'Profile Setup',
    'dashLayout.signOut': 'Sign Out',
    'dashLayout.profileCompletion': 'Profile Completion',
    'dashLayout.completeProfile': 'Complete your profile →',
    'dashLayout.displayName': 'Display name',
    'dashLayout.bio': 'Bio',
    'dashLayout.profilePhoto': 'Profile photo',
    'dashLayout.customHandle': 'Custom handle',
    'dashLayout.addContentBlocks': 'Add content blocks',
    'dashLayout.upgradePlan': 'Upgrade your plan',
    'dashLayout.unlockFeatures': 'Unlock more features and grow your audience faster.',
    'dashLayout.unlockFeaturesMobile': 'Unlock more features and grow faster.',
    'dashLayout.viewPlans': 'View Plans',
    'dashLayout.unlimitedLinks': 'Unlimited links',
    'dashLayout.customThemes': 'Custom themes',
    'dashLayout.advancedAnalytics': 'Advanced analytics',
    'dashLayout.prioritySupport': 'Priority support',
    'dashLayout.everythingInPro': 'Everything in Pro',
    'dashLayout.customDomain': 'Custom domain',
    'dashLayout.removeBranding': 'Remove branding',
    'dashLayout.apiAccess': 'API access',

    // Login / Auth
    'login.backToHome': 'Back to home',
    'login.welcomeBack': 'Welcome Back',
    'login.createAccount': 'Create Account',
    'login.resetPassword': 'Reset Password',
    'login.signInSubtitle': 'Sign in to manage your links',
    'login.signUpSubtitle': 'Sign up to create your TitiLinks page',
    'login.resetSubtitle': 'Enter your email to receive a reset link',
    'login.emailLabel': 'Email',
    'login.passwordLabel': 'Password',
    'login.emailPlaceholder': 'you@example.com',
    'login.passwordPlaceholder': '••••••••',
    'login.signIn': 'Sign In',
    'login.signUp': 'Sign up',
    'login.forgotPassword': 'Forgot password?',
    'login.sendResetLink': 'Send Reset Link',
    'login.backToSignIn': 'Back to sign in',
    'login.orContinueWith': 'Or continue with',
    'login.continueWithGoogle': 'Continue with Google',
    'login.alreadyHaveAccount': 'Already have an account?',
    'login.dontHaveAccount': "Don't have an account?",
    'login.checkYourEmail': 'Check your email',
    'login.confirmationSent': "We've sent a confirmation link to",
    'login.clickToActivate': 'Click the link to activate your account.',
    'login.didntReceive': "Didn't receive it? Check your spam folder or try again.",
    'login.resendConfirmation': 'Resend confirmation email',
    'login.resetSent': "We've sent a password reset link to",
    'login.validationEmail': 'Please enter a valid email',
    'login.validationPassword': 'Password must be at least 6 characters',
    'login.errorAlreadyRegistered': 'This email is already registered. Try signing in instead.',
    'login.errorInvalidCredentials': 'Invalid email or password. Please try again.',
    'login.newHereCta': 'New here? Create an account →',
    'login.errorGoogleFailed': 'Failed to sign in with Google',

    // Onboarding Form
    'onboarding.createYourPage': 'Create Your Page',
    'onboarding.stepOf': 'Step',
    'onboarding.of': 'of',
    'onboarding.profileDetails': 'Profile Details',
    'onboarding.themeAppearance': 'Theme & Appearance',
    'onboarding.uploadAvatar': 'Upload Avatar',
    'onboarding.avatarSizeLimit': 'Max 2MB, JPEG/PNG/GIF/WebP',
    'onboarding.displayName': 'Display Name',
    'onboarding.displayNamePlaceholder': 'Your Name',
    'onboarding.handle': 'Handle',
    'onboarding.handlePlaceholder': 'yourhandle',
    'onboarding.bioOptional': 'Bio (optional)',
    'onboarding.bioPlaceholder': 'Tell people about yourself...',
    'onboarding.continue': 'Continue',
    'onboarding.themeMode': 'Theme Mode',
    'onboarding.light': 'Light',
    'onboarding.dark': 'Dark',
    'onboarding.accentColor': 'Accent Color',
    'onboarding.preview': 'Preview',
    'onboarding.back': 'Back',
    'onboarding.createPage': 'Create Page',
    'onboarding.creating': 'Creating...',
    'onboarding.pageCreated': 'Your page has been created!',
    'onboarding.pageCreatedTitle': 'Page Created!',
    'onboarding.redirecting': 'Redirecting to your editor…',
    'onboarding.handleTaken': 'This handle is already taken',
    'onboarding.handleTakenToast': 'This handle is already taken. Please choose a different one.',
    'onboarding.avatarTooLarge': 'Avatar must be less than 2MB',
    'onboarding.avatarInvalidType': 'Only JPEG, PNG, GIF, and WebP images are allowed',
    'onboarding.failedToCreatePage': 'Failed to create page',

    // Block Editor Dialog
    'blockEditor.failedToLoad': 'Failed to load block',
    'blockEditor.unknownType': 'Unknown block type',

    // Block Item
    'blockItem.primaryCta': 'Primary CTA',
    'blockItem.productCards': 'Product Cards',
    'blockItem.featuredMedia': 'Featured Media',
    'blockItem.socialLinks': 'Social Links',
    'blockItem.links': 'Links',

    // Not Found Page
    'notFound.title': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',

    // Setup Page
    'setup.heading': 'How would you like to set up your page?',
    'setup.recommended': 'Recommended',
    'setup.aiTitle': 'Quick Start with AI',
    'setup.aiDesc': "Answer a few questions and we'll build your page automatically — links, bios, and all.",
    'setup.aiFeature1': 'AI-generated bios',
    'setup.aiFeature2': 'Pre-built link blocks',
    'setup.aiFeature3': 'Ready in 2 minutes',
    'setup.aiButton': 'Start with AI',
    'setup.manualTitle': 'Build it Myself',
    'setup.manualDesc': 'Set up your profile and add your own links step by step. AI suggestions available too.',
    'setup.manualFeature1': 'Full creative control',
    'setup.manualFeature2': 'AI copywriting hints',
    'setup.manualFeature3': 'Build at your own pace',
    'setup.manualButton': 'Manual Setup',

    // Short Link Redirect
    'shortLink.notFound': 'Link not found',
    'shortLink.error': 'Error',
    'shortLink.failedResolve': 'Failed to resolve link',
    'shortLink.somethingWrong': 'Something went wrong',
    'shortLink.redirecting': 'Redirecting...',

    // Suggest Links Dialog
    'suggestLinks.title': 'Suggest Links',
    'suggestLinks.description': 'Describe what you want to promote and AI will suggest links for your page.',
    'suggestLinks.placeholder': 'e.g. My new fitness program and supplement line',
    'suggestLinks.thinking': 'Thinking...',
    'suggestLinks.suggest': 'Suggest',
    'suggestLinks.selected': 'selected',
    'suggestLinks.deselectAll': 'Deselect All',
    'suggestLinks.selectAll': 'Select All',
    'suggestLinks.cancel': 'Cancel',
    'suggestLinks.addSelected': 'Add Selected',
    'suggestLinks.describePrompt': 'Please describe what you want to promote',
    'suggestLinks.unexpectedFormat': 'Unexpected response format',
    'suggestLinks.failedGenerate': 'Failed to generate suggestions',
    'suggestLinks.selectAtLeastOne': 'Please select at least one link',
    'suggestLinks.addedLinks': 'Added',
    'suggestLinks.link': 'link',
    'suggestLinks.links': 'links',
    'suggestLinks.failedAdd': 'Failed to add links',

    // Templates Page
    'templates.title': 'Find your perfect',
    'templates.title2': 'template',
    'templates.subtitle': 'Browse templates designed for your industry and start customizing in seconds.',
    'templates.comingSoon': 'Click any category to explore templates coming soon!',
    'templates.backToCategories': 'Back to categories',
    'templates.categoryTitle': 'Templates',
    'templates.categorySubtitle': 'Choose a template that fits your style and start building your page in minutes.',
    'templates.preview': 'Preview',
    'templates.useTemplate': 'Use This Template',
    'templates.noTemplates': 'No templates available for this category yet.',
    'templates.category.fashion': 'Fashion',
    'templates.category.healthFitness': 'Health and Fitness',
    'templates.category.influencer': 'Influencer and Creator',
    'templates.category.marketing': 'Marketing',
    'templates.category.music': 'Music',
    'templates.category.smallBusiness': 'Small Business',
    'templates.category.socialMedia': 'Social Media',
    'templates.category.sports': 'Sports',
    'templates.category.telegram': 'Telegram',
    'templates.category.whatsapp': 'Whatsapp',
  },
  es: {
    // Navbar
    'nav.products': 'Productos',
    'nav.products.linkInBio': 'Link en Bio',
    'nav.products.linkInBio.desc': 'Toda tu marca en un enlace',
    'nav.products.linkShortener': 'Acortador de Links',
    'nav.products.linkShortener.desc': 'Crea URLs cortas rastreables',
    'nav.products.qrGenerator': 'Generador QR',
    'nav.products.qrGenerator.desc': 'Genera códigos QR para cualquier link',
    'nav.templates': 'Plantillas',
    'nav.pricing': 'Precios',
    'nav.features': 'Funciones',
    'nav.login': 'Iniciar sesión',
    'nav.signup': 'Regístrate gratis',
    
    // Hero
    'hero.badge': 'Tu bio, a otro nivel',
    'hero.title1': 'Un solo link.',
    'hero.title2': 'Todo lo que eres.',
    'hero.title3': 'link poderoso.',
    'hero.subtitle': 'El link in bio que parece hecho por un diseñador.',
    'hero.description': 'Da vida a tu marca con impresionantes páginas de enlace en bio. Cada conexión es un viaje, cada clic una nueva oportunidad.',
    'hero.cta': 'Reservar',
    'hero.cta2': 'Ver Ejemplos',
    'hero.handlePlaceholder': 'tunombre',
    'hero.stat1': 'Configura en 2 min',
    'hero.stat2': 'Hecho para Creadores',
    'hero.mockup.name': 'LaCreadora 🌺',
    'hero.mockup.bio': 'Creadora de Contenido & Emprendedora ✨',
    'hero.mockup.btn1': 'Compra Mis Favoritos',
    'hero.mockup.btn2': 'Únete a Mi Equipo',
    'hero.mockup.btn3': 'Guía Gratis para Empezar',
    'hero.mockup.clicks': '+127 clics hoy',
    'hero.mockup.setup': '⚡ Configura en 2 min',
    'hero.noCreditCard': 'Sin tarjeta.',
    'hero.freeForever': 'Gratis para empezar.',
    'hero.phone.link1': 'Últimos reels',
    'hero.phone.link1sub': '@maya.rivera',
    'hero.phone.link2': 'Compra mis favoritos',
    'hero.phone.link2sub': 'Nuevo drop · quedan 48h',
    'hero.phone.link3': 'Escúchame',
    'hero.phone.link3sub': 'Spotify · Apple Music',
    'hero.phone.link4': 'Reserva una sesión',
    'hero.phone.link4sub': 'Quedan 3 lugares esta semana',
    
    // Problem Section
    'problem.title': '¿Te suena',
    'problem.title2': 'familiar?',
    'problem.subtitle': 'La mayoría de los creadores luchan con los mismos problemas frustrantes',
    'problem.item1.title': 'Enlaces dispersos, ventas perdidas',
    'problem.item1.desc': 'Tu audiencia se va antes de encontrar lo que importa. Múltiples enlaces significan múltiples oportunidades de perderlos.',
    'problem.item2.title': 'Horas perdidas en configuración',
    'problem.item2.desc': 'Construir un sitio web toma semanas. Actualizarlo toma horas. Tu contenido se mueve más rápido que tus herramientas.',
    'problem.item3.title': 'Sin idea de qué funciona',
    'problem.item3.desc': 'Estás a ciegas. ¿Qué enlaces convierten? ¿Dónde abandonan los visitantes? Los bios tradicionales no te dicen nada.',
    
    // Solution Section
    'solution.title': 'Tu enlace bio,',
    'solution.title2': 'elevado',
    'solution.description': 'TitiLinks transforma tu único enlace bio en una tienda dinámica y rastreable que convierte seguidores en clientes—en minutos, no meses.',
    'solution.feature1': 'Diseño hermoso, móvil primero',
    'solution.feature2': 'Analíticas y seguimiento integrados',
    'solution.feature3': 'Cambio de modo para diferentes audiencias',
    'solution.feature4': 'Tiempos de carga ultrarrápidos',
    'solution.clicks': '+127 clics hoy',
    'solution.mockup.name': 'SoyCreadora 🥰',
    'solution.mockup.bio': 'Bienvenidos a mi mundo ✨',
    
    // Features Section
    'features.title': 'Todo lo que necesitas para',
    'features.title2': 'convertir',
    'features.subtitle': 'Funciones poderosas que te ayudan a convertir clics en clientes',
    'features.themes.title': 'Temas Impresionantes',
    'features.themes.desc': 'Elige entre hermosos preajustes o personaliza colores, fuentes y diseños para que coincidan perfectamente con tu marca.',
    'features.analytics.title': 'Analíticas Profundas',
    'features.analytics.desc': 'Rastrea cada clic, vista y conversión. Sabe exactamente de dónde viene tu audiencia y qué quieren.',
    'features.modes.title': 'Cambio de Modo',
    'features.modes.desc': 'Ofrece a los visitantes una segunda página con sus propios enlaces—cambian con un clic.',
    'features.speed.title': 'Ultrarrápido',
    'features.speed.desc': 'Tiempos de carga de menos de 100ms. Tu página carga antes de que puedan parpadear.',
    'features.privacy.title': 'Privacidad Primero',
    'features.privacy.desc': 'Tus datos son tuyos. No vendemos tus analíticas ni compartimos información de visitantes.',
    'features.builder.title': 'Constructor Manual o con IA',
    'features.builder.desc': 'Construye tu página a tu manera—créala manualmente con control total, o deja que la IA la cree por ti en segundos.',
    
    // How It Works
    'how.title': 'En vivo en',
    'how.title2': '3 simples pasos',
    'how.subtitle': 'De registro a compartir en menos de 5 minutos',
    'how.step1.title': 'Regístrate en segundos',
    'how.step1.desc': 'Crea tu cuenta con email o Google. No se requiere tarjeta de crédito.',
    'how.step2.title': 'Personaliza tu página',
    'how.step2.desc': 'Agrega tus enlaces, productos y medios. Elige un tema que coincida con tu estilo.',
    'how.step3.title': 'Comparte y crece',
    'how.step3.desc': 'Pon tu enlace en tu bio y mira cómo llegan las analíticas. Optimiza y convierte.',
    
    // Testimonials
    'testimonials.title': 'Amado por',
    'testimonials.title2': 'creadores',
    'testimonials.subtitle': 'Únete a miles de creadores que han mejorado su enlace bio',
    
    // Stats
    'stats.title': 'Resultados que',
    'stats.title2': 'hablan',
    'stats.subtitle': 'Números reales de creadores reales',
    'stats.ctr': 'Mayor CTR',
    'stats.ctr.desc': 'vs. enlaces bio tradicionales',
    'stats.conversions': 'Más Conversiones',
    'stats.conversions.desc': 'con cambio de modo',
    'stats.load': 'Tiempo de Carga Prom.',
    'stats.load.desc': 'distribuido globalmente',
    
    // Pricing
    'pricing.title': 'Precios',
    'pricing.title2': 'simples',
    'pricing.title3': 'y transparentes',
    'pricing.subtitle': 'Comienza gratis y escala mientras creces. Sin tarifas ocultas.',
    'pricing.monthly': 'Mensual',
    'pricing.annual': 'Anual',
    'pricing.save': 'Ahorra hasta 40%',
    'pricing.period.monthly': '/mes',
    'pricing.period.annual': '/mes, facturado anualmente',
    'pricing.free': 'Gratis',
    'pricing.free.period': 'para siempre',
    'pricing.free.desc': 'Perfecto para comenzar',
    'pricing.pro': 'Pro',
    'pricing.pro.desc': 'Para creadores serios',
    'pricing.premium': 'Premium',
    'pricing.premium.desc': 'Para equipos y agencias',
    'pricing.popular': 'Más Popular',
    'pricing.cta.free': 'Comienza Gratis',
    'pricing.cta.pro': 'Ir a Pro',
    'pricing.cta.premium': 'Contactar Ventas',
    'pricing.comingSoon': 'Próximamente',
    
    // CTA
    'cta.badge': 'Comienza gratis hoy',
    'cta.title': '¿Listo para',
    'cta.title2': 'subir de nivel',
    'cta.title3': 'tu bio?',
    'cta.description': 'Únete a miles de creadores que ya hicieron el cambio. Tu nuevo enlace-en-bio está a un clic de distancia.',
    'cta.button': 'Comienza Gratis Hoy',
    'cta.button2': 'Ver Demo',
    'cta.note': 'Sin tarjeta de crédito · Gratis para siempre · Configura en 2 minutos',
    
    // Footer
    'footer.tagline': 'El enlace-en-bio para creadores que venden. Convierte clics en clientes.',
    'footer.product': 'Producto',
    'footer.company': 'Compañía',
    'footer.resources': 'Recursos',
    'footer.legal': 'Legal',
    'footer.copyright': 'Todos los derechos reservados.',
    'footer.made': 'Hecho con ✨ para creadores en todo el mundo',

    // Onboarding Flow
    'onboardingFlow.stepStyle': 'Estilo',
    'onboardingFlow.stepProfile': 'Perfil',
    'onboardingFlow.stepLayout': 'Diseño',
    'onboardingFlow.stepVibe': 'Vibra',
    'onboardingFlow.stepLinks': 'Enlaces',
    'onboardingFlow.stepLive': 'En vivo',
    'onboardingFlow.chooseStyle': 'Elige tu estilo',
    'onboardingFlow.chooseStyleDesc': 'Escoge un diseño que combine con tu marca.',
    'onboardingFlow.styleClassic': 'Clásico',
    'onboardingFlow.styleClassicDesc': 'Diseño limpio centrado con avatar redondo y enlaces apilados.',
    'onboardingFlow.styleHero': 'Hero',
    'onboardingFlow.styleHeroDesc': 'Foto de cabecera llamativa con tu nombre y enlaces debajo.',
    'onboardingFlow.styleFullBleed': 'Pantalla completa',
    'onboardingFlow.styleFullBleedDesc': 'Foto de fondo a pantalla completa con contenido superpuesto.',
    'onboardingFlow.continue': 'Continuar',
    'onboardingFlow.back': 'Volver',
    'onboardingFlow.skipForNow': 'Saltar por ahora',
    'onboardingFlow.yourProfile': 'Tu perfil',
    'onboardingFlow.yourProfileDesc': 'Cuéntanos un poco sobre ti.',
    'onboardingFlow.displayName': 'Nombre para mostrar',
    'onboardingFlow.displayNamePlaceholder': 'Tu nombre',
    'onboardingFlow.username': 'Nombre de usuario',
    'onboardingFlow.usernamePlaceholder': 'tunombre',
    'onboardingFlow.uploadPhoto': 'Subir foto',
    'onboardingFlow.changePhoto': 'Cambiar foto',
    'onboardingFlow.photoNudgeTitle': '¿Agregar una foto?',
    'onboardingFlow.photoNudgeBodyHero': 'Tu página se ve mejor con una foto. ¿Quieres agregar una ahora?',
    'onboardingFlow.photoNudgeBodyFullBleed': 'Tu página de fondo completo necesita una foto de fondo. ¿Quieres agregar una ahora?',
    'onboardingFlow.photoNudgeAdd': 'Agregar foto',
    'onboardingFlow.photoNudgeNotNow': 'Ahora no',
    'onboardingFlow.photoSkipTitle': 'Sin foto — no hay problema',
    'onboardingFlow.photoSkipBody': 'Puedes agregar una en cualquier momento desde Editar perfil en tu panel.',
    'onboardingFlow.photoSkipContinue': 'Entendido, continuar',
    'onboardingFlow.stepButtons': 'Botones',
    'onboardingFlow.chooseButtons': 'Elige tus botones',
    'onboardingFlow.chooseButtonsDesc': 'Elige el estilo de los botones de tu página. Vista previa sobre tu foto.',
    'onboardingFlow.accentColor': 'Color de acento',
    'onboardingFlow.buttonSizeLarge': 'Grande',
    'onboardingFlow.buttonSizeSmall': 'Pequeño',
    'onboardingFlow.buttonShape': 'Forma del botón',
    'onboardingFlow.pickVibe': 'Elige tu vibra',
    'onboardingFlow.pickVibeDesc': 'Personaliza la apariencia de tu página.',
    'onboardingFlow.background': 'Fondo',
    'onboardingFlow.buttonStyle': 'Estilo de botón',
    'onboardingFlow.fontChoice': 'Tipografía',
    'onboardingFlow.socialPlatforms': 'Plataformas sociales',
    'onboardingFlow.addLinks': 'Agrega tus enlaces',
    'onboardingFlow.addLinksDesc': 'Pega tus URLs de redes sociales abajo.',
    'onboardingFlow.noSocialsSelected': 'Vuelve atrás para seleccionar tus plataformas sociales.',
    'onboardingFlow.yourSocialPlatforms': 'Tus plataformas sociales',
    'onboardingFlow.yourSocialPlatformsDesc': 'Toca para agregar las plataformas en las que estás. Agregarás tus enlaces en el editor.',
    'onboardingFlow.youreLive': '¡Estás en vivo!',
    'onboardingFlow.youreLiveDesc': 'Tu página está lista para compartir con el mundo.',
    'onboardingFlow.shareLink': 'Compartir mi enlace',
    'onboardingFlow.goToDashboard': 'Ir a mi panel',
    'onboardingFlow.saveFailed': 'Error al guardar. Intenta de nuevo.',
    'onboardingFlow.usernameTaken': 'Este nombre de usuario ya está en uso.',


    // Design Editor
    'design.title': 'Ajustes de diseño',
    'design.save': 'Guardar',
    'design.designTools': 'Herramientas de diseño',
    'design.pageStyle': 'Estilo de Página',
    'design.pageStyleDesc': 'Elige cómo se ve tu perfil a los visitantes',
    'design.styleClassic': 'Clásico',
    'design.styleClassicDesc': 'Avatar circular, centrado',
    'design.styleHero': 'Hero',
    'design.styleHeroDesc': 'Foto completa con nombre encima',
    'design.styleFullBleed': 'Pantalla Completa',
    'design.styleFullBleedDesc': 'Foto inmersiva a pantalla completa',
    'design.templateGallery': 'Galería de plantillas',
    'design.browseTemplates': 'Explorar plantillas',
    'design.canvaStudio': 'Canva Studio',
    'design.comingSoon': 'Próximamente',
    'design.checking': 'Verificando...',
    'design.importDesigns': 'Importar diseños',
    'design.connectToImport': 'Conectar para importar',
    'design.canvaSetupHelp': 'Ayuda de configuración de Canva - Clic para expandir',
    'design.canvaSetupIntro': 'Conecta Canva para diseñar encabezados y fondos personalizados:',
    'design.canvaStep1Prefix': 'En',
    'design.canvaStep1Create': 'crea una',
    'design.canvaConnect': 'Canva Connect',
    'design.canvaStep1Suffix': 'integración',
    'design.canvaStep2': 'Agrega URL de redirección:',
    'design.canvaStep3': 'Habilita los scopes:',
    'design.canvaStep3And': 'y',
    'design.canvaStep4Copy': 'Copia',
    'design.canvaClientId': 'Client ID',
    'design.canvaClientSecret': 'Client Secret',
    'design.canvaStep4Suffix': 'en las variables de entorno',
    'design.canvaNote': 'Usa "Your integrations" no "Your apps" en Canva.',
    'design.noteLabel': 'Nota:',
    'design.mfaRequired': 'MFA requerido',
    'design.mfaDesc': 'Habilita MFA en Canva Ajustes \u2192 Inicio de sesión, luego reintenta.',
    'design.retry': 'Reintentar',
    'design.canvaImports': 'Importaciones de Canva',
    'design.disconnect': 'Desconectar',
    'design.background': 'Fondo',
    'design.header': 'Encabezado',
    'design.replace': 'Reemplazar',
    'design.remove': 'Eliminar',
    'design.headerLayout': 'Diseño de encabezado',
    'design.layoutOverlay': 'Overlay',
    'design.layoutOverlayDesc': 'Texto sobre imagen',
    'design.layoutCard': 'Tarjeta',
    'design.layoutCardDesc': 'Imagen en tarjeta',
    'design.layoutSplit': 'Dividido',
    'design.layoutSplitDesc': 'Estilo vitrina',
    'design.layoutCinematic': 'Cinemático',
    'design.layoutCinematicDesc': 'Foto héroe completa',
    'design.layoutImmersive': 'Inmersivo',
    'design.layoutImmersiveDesc': 'Foto de fondo completa',
    'design.onlineIndicator': 'Indicador en línea',
    'design.lastImportedCanva': 'Última importación de Canva',
    'design.importAnother': 'Importar otro diseño',
    'design.addAnotherCanva': 'Agregar otro diseño de Canva',
    'design.chooseCanvaDesign': 'Elegir un diseño de Canva',
    'design.canvaErrorMfa': 'MFA requerido',
    'design.canvaErrorMfaDesc': 'Tu cuenta de Canva requiere autenticación multifactor.',
    'design.canvaErrorPermission': 'Permiso requerido',
    'design.canvaErrorPermissionDesc': 'La creación de diseños requiere permisos adicionales.',
    'design.reconnectCanva': 'Reconectar Canva',
    'design.canvaErrorGeneric': 'Error',
    'design.canvaErrorGenericDesc': 'Algo salió mal. Por favor intenta de nuevo.',
    'design.dismiss': 'Descartar',
    'design.quickStartPresets': 'Plantillas',
    'design.mySavedPresets': 'Mis preajustes guardados',
    'design.saveCurrent': 'Guardar actual',
    'design.saveThemePreset': 'Guardar preajuste de tema',
    'design.saveThemePresetDesc': 'Guarda tus ajustes de tema actuales como un preajuste reutilizable.',
    'design.presetName': 'Nombre del preajuste',
    'design.presetPlaceholder': 'ej., Mi tema de marca',
    'design.cancel': 'Cancelar',
    'design.savePreset': 'Guardar preajuste',
    'design.noPresetsYet': 'Aún no hay preajustes guardados. ¡Personaliza tu tema y guárdalo!',
    'design.microinteractions': 'Microinteracciones',
    'design.microinteractionsDesc': 'Animaciones de elevación y presión',
    'design.microinteractionsNote': 'Los usuarios con "reducir movimiento" activado en su dispositivo no verán animaciones sin importar esta configuración.',
    'design.matchStyles': 'Adaptar estilos al fondo',
    'design.matchStylesDesc': 'Ajustar colores automáticamente para legibilidad',
    'design.matchStylesNote': 'Cuando está activado, ajusta automáticamente la opacidad de la superposición y el color del texto para mejor legibilidad en fondos con imagen.',
    'design.tabBackground': 'Fondo',
    'design.tabButtons': 'Botones',
    'design.tabTypography': 'Tipografía',
    'design.tabTitle': 'Título',
    'design.tabFont': 'Fuente',
    'design.backgroundColor': 'Color de fondo',
    'design.mainTextColor': 'Color del texto principal',
    'design.chooseFont': 'Elegir fuente',
    'design.update': 'Actualizar',
    'design.resetToDefault': 'Restablecer',
    'design.eyedropper': 'Elegir color de la pantalla',
    'design.backgroundType': 'Tipo de fondo',
    'design.solidColor': 'Color sólido',
    'design.gradient': 'Degradado',
    'design.image': 'Imagen',
    'design.choosePresetGradient': 'Elegir un degradado preestablecido',
    'design.backgroundImage': 'Imagen de fondo',
    'design.uploading': 'Subiendo...',
    'design.uploadImage': 'Subir imagen',
    'design.uploadNote': 'Máx 5MB. Soportado: JPEG, PNG, GIF, WebP',
    'design.overlaySettings': 'Ajustes de superposición',
    'design.overlayColor': 'Color de superposición',
    'design.overlayOpacity': 'Opacidad de superposición:',
    'design.preview': 'Vista previa',
    'design.yourContentHere': 'Tu contenido aquí',
    'design.buttonShape': 'Forma del botón',
    'design.pill': 'Píldora',
    'design.rounded': 'Redondeado',
    'design.square': 'Cuadrado',
    'design.fillColor': 'Color de relleno',
    'design.textColor': 'Color de texto',
    'design.enableBorder': 'Activar borde',
    'design.borderColor': 'Color del borde',
    'design.enableShadow': 'Activar sombra',
    'design.density': 'Densidad',
    'design.compact': 'Compacto',
    'design.normal': 'Normal',
    'design.roomy': 'Espacioso',
    'design.sampleButton': 'Botón de ejemplo',
    'design.fontFamily': 'Familia de fuente',
    'design.systemDefault': 'Predeterminado del sistema',
    'design.serif': 'Serif',
    'design.monospace': 'Monoespaciado',
    'design.sampleHeading': 'Título de ejemplo',
    'design.sampleText': 'Así es como se verá tu texto en la página.',
    'design.livePreview': 'Vista previa en vivo',
    'design.designSaved': '¡Diseño guardado!',
    'design.designSaveFailed': 'Error al guardar diseño',
    'design.presetSaved': '¡Preajuste guardado!',
    'design.presetSaveFailed': 'Error al guardar preajuste',
    'design.presetDeleted': 'Preajuste eliminado',
    'design.presetDeleteFailed': 'Error al eliminar preajuste',
    'design.canvaConnected': '¡Canva conectado exitosamente!',
    'design.canvaConnectFailed': 'Error al conectar Canva',
    'design.canvaDisconnected': 'Canva desconectado',
    'design.canvaDisconnectFailed': 'Error al desconectar Canva',
    'design.canvaNoAuthUrl': 'No se recibió URL de autorización',
    'design.canvaConnectInitFailed': 'Error al iniciar la conexión con Canva',
    'design.canvaCreateFailed': 'Error al crear diseño en Canva',
    'design.canvaDesignUrlFailed': 'Error al obtener URL de diseño de Canva',
    'design.canvaOpeningEditor': 'Abriendo editor de Canva...',
    'design.imgSizeError': 'La imagen debe ser de 5MB o menos',
    'design.imgTypeError': 'Solo se permiten imágenes JPEG, PNG, GIF y WebP',
    'design.bgImageUploaded': '¡Imagen de fondo subida!',
    'design.bgUploadFailed': 'Error al subir imagen',
    'design.timeJustNow': 'Justo ahora',
    'design.timeMinsAgo': 'm atrás',
    'design.timeHoursAgo': 'h atrás',
    'design.timeDaysAgo': 'd atrás',
    'design.gradientMidnight': 'Midnight',
    'design.gradientSunset': 'Sunset',
    'design.gradientOcean': 'Ocean',
    'design.canvaDeveloperPortal': 'Portal de desarrolladores de Canva',

    // Editor Child Components (GoalsPanel, LinkTools, BlockList)
    'goals.title': 'Metas',
    'goals.primaryOffer': 'Meta de oferta principal',
    'goals.page2Goal': 'Meta de página 2',
    'goals.selectItem': 'Selecciona un enlace',
    'goals.noGoalSet': 'Sin meta configurada',
    'goals.trackPrimary': 'Rastrea clics a tu oferta principal de ventas.',
    'goals.trackPage2': 'Rastrea clics al enlace principal de tu página 2.',
    'goals.addItemsFirst': 'Agrega enlaces primero para configurar metas.',
    'goals.save': 'Guardar metas',
    'goals.saved': 'Metas guardadas',
    'goals.saveFailed': 'Error al guardar metas',
    'goals.loadFailed': 'Error al cargar elementos',
    'linkTools.createShortLink': 'Crear enlace corto',
    'linkTools.shortLinkCreated': 'Enlace corto creado',
    'linkTools.shortLinkReady': 'Tu enlace corto está listo',
    'linkTools.copied': 'Copiado',
    'linkTools.copiedDesc': 'URL corta copiada al portapapeles',
    'linkTools.copyFailed': 'Error al copiar al portapapeles',
    'linkTools.downloaded': 'Descargado',
    'linkTools.downloadFailed': 'Error al descargar código QR',
    'linkTools.downloadPng': 'Descargar PNG',
    'linkTools.downloadSvg': 'Descargar SVG',
    'linkTools.error': 'Error',
    'linkTools.loginRequired': 'Debes iniciar sesión para crear enlaces cortos',
    'blocks.loadFailed': 'Error al cargar bloques',
    'blocks.orderUpdated': 'Orden de bloques actualizado',
    'blocks.orderFailed': 'Error al actualizar orden de bloques',
    'blocks.enabled': 'Bloque activado',
    'blocks.disabled': 'Bloque desactivado',
    'blocks.toggleFailed': 'Error al actualizar bloque',
    'blocks.primary_cta.title': 'CTA Principal',
    'blocks.primary_cta.subtitle': 'Tu botón principal de llamada a la acción',
    'blocks.product_cards.title': 'Productos',
    'blocks.product_cards.subtitle': 'Muestra tus productos',
    'blocks.featured_media.title': 'Medios Destacados',
    'blocks.featured_media.subtitle': 'Fotos y enlaces de video',
    'blocks.video_feed.title': 'Feeds de Video',
    'blocks.video_feed.subtitle': 'Tus ultimos videos, actualizados automaticamente',
    'blocks.text.title': 'Texto',
    'blocks.text.subtitle': 'Agrega un titulo y un parrafo',
    'blockEditor.heading': 'Título (opcional)',
    'blockEditor.headingPlaceholder': 'ej. Mis Cursos',
    'blockEditor.text': 'Texto',
    'blockEditor.textPlaceholder': 'Escribe tu párrafo...',
    'blockEditor.bio': 'Biografía',
    'blockEditor.bioPlaceholder': 'Escribe algo sobre ti...',
    'blockEditor.styling': 'Estilo:',
    'blockEditor.headingTab': 'Título',
    'blockEditor.textTab': 'Texto',
    'blockEditor.font': 'Fuente',
    'blockEditor.defaultFont': 'Predeterminada (fuente de la página)',
    'blockEditor.weight': 'Grosor',
    'blockEditor.bold': 'Negrita',
    'blockEditor.size': 'Tamaño',
    'blockEditor.small': 'Pequeño',
    'blockEditor.medium': 'Mediano',
    'blockEditor.large': 'Grande',
    'blockEditor.alignment': 'Alineación',
    'blockEditor.left': 'Izquierda',
    'blockEditor.center': 'Centro',
    'blockEditor.right': 'Derecha',
    'blockEditor.cancel': 'Cancelar',
    'blockEditor.save': 'Guardar',
    'blockEditor.textSaved': 'Texto guardado',
    'blockEditor.textLoadError': 'No se pudo cargar el texto',
    'blockEditor.textSaveError': 'No se pudo guardar el texto',
    'blockEditor.bioSaved': 'Biografía guardada',
    'blockEditor.bioLoadError': 'No se pudo cargar la biografía',
    'blockEditor.bioSaveError': 'No se pudo guardar la biografía',
    'blocks.social_links.title': 'Plataformas Sociales',
    'blocks.social_links.subtitle': 'Agrega tus plataformas sociales',
    'blocks.links.title': 'Enlaces destacados',
    'blocks.links.subtitle': 'Agregar enlace',
    'blocks.email_subscribe.title': 'Captura de Email',
    'blocks.email_subscribe.subtitle': 'Recolecta emails de visitantes',
    'blocks.social_icon_row.title': 'Iconos Sociales',
    'blocks.social_icon_row.subtitle': 'Fila de iconos de redes sociales',
    'blocks.hero_card.title': 'Tarjeta Hero',
    'blocks.hero_card.subtitle': 'Sección hero del perfil',
    'blocks.content_section.title': 'Sección de Contenido',
    'blocks.content_section.subtitle': 'Bloque de texto y contenido',
    'blocks.gallery.title': 'Galería',
    'blocks.gallery.subtitle': 'Galería de fotos',
    'blocks.carousel.title': 'Carrusel',
    'blocks.carousel.subtitle': 'Fila deslizable de tarjetas de enlace',
    'blocks.bio.title': 'Biografía',
    'blocks.bio.subtitle': 'Cuéntales sobre ti',

    // Gallery & shared block strings
    'gallery.label': 'Galería',
    'gallery.photo': 'foto',
    'gallery.photos': 'fotos',
    'gallery.uploadFailed': 'Error al subir la foto',
    'emptyState.noContent': 'Aún no hay contenido',
    'emailSubscribe.defaultTitle': 'Mantente al día',
    'emailSubscribe.defaultPlaceholder': 'tu@email.com',
    'emailSubscribe.defaultButton': 'Suscribirse',
    'emailSubscribe.defaultSuccess': '¡Gracias por suscribirte!',
    'emailSubscribe.defaultName': 'Tu nombre',
    'emailSubscribe.errorUnable': 'No se puede suscribir',
    'emailSubscribe.errorInvalidEmail': 'Por favor ingresa un correo válido',
    'emailSubscribe.errorGeneric': 'Error al suscribirse',
    'emailSubscribe.errorRetry': 'Error al suscribirse. Por favor intenta de nuevo.',
    'contentSection.viewAll': 'Ver todo',
    'editor.changePhotoToast': 'Ve a Ajustes para cambiar tu foto de perfil',

    // Default block content (placeholders created during onboarding)
    'content.shopMyCollection': 'Compra Mi Colección',
    'content.newArrivalsEveryWeek': 'Nuevas llegadas cada semana',
    'content.myWebsite': 'Mi Sitio Web',
    'content.checkOutMyWebsite': 'Visita mi sitio web',
    'content.latestBlogPost': 'Última Publicación',
    'content.readMyLatestContent': 'Lee mi contenido más reciente',
    'content.workWithMe': 'Trabaja Conmigo',
    'content.collaborationsPartnerships': 'Colaboraciones y alianzas',
    'content.productOne': 'Producto Uno',
    'content.yourBestSeller': 'Tu más vendido',
    'content.productTwo': 'Producto Dos',
    'content.newArrival': 'Nueva llegada',
    'content.productThree': 'Producto Tres',
    'content.fanFavorite': 'Favorito del público',
    'content.bookConsultation': 'Reservar Consulta',
    'content.letsWorkTogether': 'Trabajemos juntos',
    'content.myShowreel': 'Mi Showreel',
    'content.watchMyLatestWork': 'Mira mi último trabajo',
    'content.portfolio': 'Portafolio',
    'content.viewMyFullPortfolio': 'Ver mi portafolio completo',
    'content.myResume': 'Mi Currículum',
    'content.downloadMyCv': 'Descargar mi CV',
    'content.pressKit': 'Kit de Prensa',
    'content.mediaResources': 'Recursos para medios',
    'content.testimonials': 'Testimonios',
    'content.whatClientsSay': 'Lo que dicen los clientes',
    'content.followMeOnTiktok': 'Sígueme en TikTok',
    'content.followMeOnInstagram': 'Sígueme en Instagram',
    'content.subscribeToMyChannel': 'Suscríbete a mi canal',
    'content.connectProfessionally': 'Conecta profesionalmente',
    'content.followMyContent': 'Sigue mi contenido',
    'content.stayUpToDate': 'Mantente al día',
    'content.thanksForSubscribing': '¡Gracias por suscribirte!',
    'content.subscribe': 'Suscribirse',
    'content.shopMyFavorites': 'Compra Mis Favoritos',
    'content.exclusiveDeals': 'Ofertas exclusivas para ti',
    'content.becomeACreator': 'Conviértete en Creador',
    'content.joinAffiliateProgram': 'Únete a mi programa de afiliados',
    'content.shopMyGamingGear': 'Compra Mi Equipo Gaming',
    'content.theExactSetup': 'El equipo exacto que uso',
    'content.joinMyAffiliateProgram': 'Únete a Mi Programa de Afiliados',
    'content.earnWhileYouGame': 'Gana mientras juegas',
    'content.shopMySupplements': 'Compra Mis Suplementos',
    'content.whatIUseDaily': 'Lo que uso a diario',
    'content.joinMyCoachingTeam': 'Únete a Mi Equipo de Coaching',
    'content.buildYourFitnessBusiness': 'Construye tu negocio fitness',
    'content.streamMyMusic': 'Escucha Mi Música',
    'content.availableOnAllPlatforms': 'Disponible en todas las plataformas',
    'content.bookingCollaborations': 'Reservas y colaboraciones',
    'content.shopMyRecommendations': 'Compra Mis Recomendaciones',
    'content.curatedForYou': 'Seleccionado para ti',
    'content.joinMyTeam': 'Únete a Mi Equipo',
    'content.learnToEarnOnline': 'Aprende a ganar en línea',
    'content.subscribeNow': 'Suscríbete Ahora',
    'content.unlockPremiumContent': 'Desbloquea contenido premium',
    'content.startCreating': 'Empieza a Crear',
    'content.joinReferralProgram': 'Únete a mi programa de referidos',
    'content.featuredContent1': 'Contenido Destacado 1',
    'content.featuredContent2': 'Contenido Destacado 2',
    'content.featuredContent3': 'Contenido Destacado 3',
    'content.primaryCta': 'CTA Principal',
    'content.products': 'Productos',
    'content.socialLinks': 'Redes Sociales',
    'content.links': 'Enlaces',
    'content.featuredMedia': 'Media Destacada',

    // Editor Page
    'editor.title': 'Editor de enlaces',
    'editor.editing': 'Editando',
    'editor.viewPage': 'Ver página',
    'editor.content': 'Contenido',
    'editor.design': 'Diseño',
    'editor.pages': 'Páginas',
    'editor.page1Label': 'Etiqueta página 1',
    'editor.page2Label': 'Etiqueta página 2',
    'editor.page1': 'Página 1',
    'editor.page2': 'Página 2',
    'editor.configureFirst': 'Configura el contenido de tu primera página.',
    'editor.configureSecond': 'Configura el contenido de tu segunda página.',
    'editor.stickyCta': 'CTA fijo',
    'editor.stickyCtaDesc': 'Mostrar CTA flotante después del scroll',
    'editor.blocks': 'Bloques',
    'editor.suggestLinks': 'Sugerir enlaces',
    'editor.noMode': 'No se encontró el modo. Recarga la página.',
    'editor.shareLinks': 'Compartir enlaces',
    'editor.defaultLink': 'Enlace predeterminado',
    'editor.defaultLinkDesc': 'Enlace predeterminado que detecta automáticamente qué página mostrar.',
    'editor.forcePage2': 'Fuerza la página 2 sin importar la referencia.',
    'editor.linkTools': 'Herramientas de enlace',
    'editor.link': 'Enlace',
    'editor.refreshPreview': 'Actualizar vista previa',
    'editor.labelUpdated': 'Etiqueta actualizada',
    'editor.labelFailed': 'Error al actualizar etiqueta',
    'editor.copied': '¡Copiado al portapapeles!',
    'editor.copyFailed': 'Error al copiar',
    'editor.stickyEnabled': 'CTA fijo activado',
    'editor.stickyDisabled': 'CTA fijo desactivado',
    'editor.settingFailed': 'Error al actualizar ajuste',
    'editor.loadFailed': 'Error al cargar datos de la página',
    'editor.viewLive': 'Ver en vivo',
    'editor.addContent': 'Agregar contenido',
    'editor.changePhoto': 'Cambiar foto de perfil',
    'editor.previewPhoto': 'Vista previa',
    'editor.savePhoto': 'Guardar foto',
    'editor.cancel': 'Cancelar',
    'editor.editPhoto': 'Editar foto',
    'editor.chooseEditMethod': '\u00bfC\u00f3mo quieres editar tu foto?',
    'editor.editManually': 'Editar manualmente',
    'editor.cropImage': 'Recortar Imagen',
    'editor.choosePage2Photo': 'Elige una foto para la Página 2',
    'editor.uploadPhoto': 'Subir Foto',
    'editor.editCurrentPhoto': 'Editar foto actual',
    'editor.newPhoto': 'Nueva foto',
    'editor.useAiCrop': 'Recorte con IA',
    'editor.useOriginal': 'Usar Original',
    'editor.aiAutoCrop': 'Recorte AI autom\u00e1tico',
    'editor.aiAnalyzing': 'AI est\u00e1 analizando tu foto...',
    'editor.aiCropFailed': 'Recorte AI fall\u00f3, intenta editar manualmente',
    'editor.dragToPosition': 'Arrastra para reposicionar',
    'editor.done': 'Listo',
    'editor.editSocial': 'Editar redes sociales',
    'editor.blocksLabel': 'Bloques',
    'editor.failedToggle': 'Error al actualizar bloque',
    'editor.failedReorder': 'Error al reordenar bloques',
    'editor.linkRemoved': 'Enlace eliminado',
    'editor.failedDelete': 'Error al eliminar enlace',
    'editor.nameHandleCard': 'Nombre y Handle',
    'editor.socialIconsCard': 'Íconos Sociales',
    'editor.nameSize': 'Tamaño del Nombre',
    'editor.handleSize': 'Tamaño del Handle',
    'editor.nameColor': 'Color del Nombre',
    'editor.handleColor': 'Color del Handle',
    'editor.padding': 'Espaciado',
    'editor.iconSize': 'Tamaño de Ícono',
    'editor.nameHandleGap': 'Espacio de Texto',

    // Profile Dashboard
    'dashboard.addContent': 'Agregar contenido',
    'dashboard.myLinks': 'Mis enlaces',
    'dashboard.managePlatforms': 'Administrar plataformas',
    'dashboard.managePlatformsDesc': 'Agrega o edita enlaces de plataformas',
    'dashboard.featuredLinks': 'Enlaces destacados',
    'dashboard.featuredLinksDesc': 'Agregar enlace',
    'dashboard.primaryCta': 'CTA principal',
    'dashboard.primaryCtaDesc': 'Tu botón de acción principal',
    'dashboard.appearance': 'Apariencia',
    'dashboard.addHeader': 'Agregar encabezado',
    'dashboard.addHeaderDesc': 'Agrega títulos personalizados sobre tus enlaces',
    'dashboard.profileCustomization': 'Personalización de perfil',
    'dashboard.profileCustomizationDesc': 'Elige fuentes, fondo y colores de texto',
    'dashboard.videoProfile': 'Video de perfil',
    'dashboard.videoProfileDesc': 'Agrega video a tu imagen de perfil',
    'dashboard.nameEffects': 'Nombre y usuario',
    'dashboard.nameEffectsDesc': 'Añade sombra o contorno para que tu nombre sea legible',
    'dashboard.pages': 'Páginas',
    'dashboard.pagesDesc': 'Agrega una segunda página que los visitantes pueden ver',
    'dashboard.videoFeeds': 'Feeds de Video',
    'dashboard.videoFeedsDesc': 'Muestra tus ultimos videos de YouTube (Instagram y TikTok pronto)',
    'dashboard.ecommerce': 'E-Commerce',
    'dashboard.newMerch': 'Nuevo producto',
    'dashboard.newMerchDesc': 'Agregar producto',
    'dashboard.products': 'Productos',
    'dashboard.digitalProducts': 'Productos digitales',
    'dashboard.digitalProductsDesc': 'Administrar productos digitales',
    'dashboard.lockedProducts': 'Productos bloqueados',
    'dashboard.lockedProductsDesc': 'Administrar productos bloqueados',
    'dashboard.events': 'Eventos',
    'dashboard.createEvent': 'Crear evento personalizado',
    'dashboard.createEventDesc': 'Agregar evento personalizado',
    'dashboard.forms': 'Formularios',
    'dashboard.createForm': 'Crear formulario',
    'dashboard.createFormDesc': 'Agregar formulario personalizado',
    'dashboard.analytics': 'Analíticas',
    'dashboard.trackingPixels': 'Píxeles de rastreo',
    'dashboard.trackingPixelsDesc': 'Agrega etiquetas de Meta, TikTok o GA',
    'dashboard.comingSoon': '¡Próximamente!',
    'dashboard.openDesignTab': 'Abre la pestaña de Diseño',
    'dashboard.templateGallery': 'Galería de plantillas',
    'dashboard.templateGalleryDesc': 'Explora y aplica plantillas de página',
    'dashboard.noMode': 'No se encontró modo',
    'dashboard.blockNotCreated': 'Este bloque aún no ha sido creado.',
    'dashboard.failedOpen': 'Error al abrir editor',

    // Analytics Page
    'analytics.title': 'Analíticas',
    'analytics.subtitle': 'Rastrea el rendimiento de tu página',
    'analytics.views7d': 'Vistas (7d)',
    'analytics.clicks7d': 'Clics (7d)',
    'analytics.last30d': 'últimos 30d',
    'analytics.clicks': 'clics',
    'analytics.goalPerformance': 'Rendimiento de metas',
    'analytics.primaryOfferGoal': 'Meta de oferta principal',
    'analytics.goal': 'Meta',
    'analytics.setGoals': 'Configurar metas',
    'analytics.setGoalsDesc': 'Configura metas para rastrear el rendimiento de conversiones',
    'analytics.notSet': 'Sin configurar',
    'analytics.topDestinations': 'Destinos principales',
    'analytics.noClicks': 'Aún no se han registrado clics salientes',
    'analytics.trafficSources': 'Fuentes de tráfico',
    'analytics.otherDirect': 'Otro / Directo',
    'analytics.noTraffic': 'Aún no hay datos de tráfico',
    'analytics.modeDistribution': 'Distribución de modos',
    'analytics.noViews': 'Aún no se han registrado vistas',
    'analytics.ofTraffic': 'del tráfico',
    'analytics.views': 'vistas',
    'analytics.ctr': 'CTR',
    'analytics.shortLinks': 'Enlaces cortos',
    'analytics.totalClicks': 'Clics totales:',
    'analytics.code': 'Código',
    'analytics.destination': 'Destino',
    'analytics.lastClick': 'Último clic',
    'analytics.noShortLinks': 'Aún no se han creado enlaces cortos',

    // Settings Page
    'settings.title': 'Ajustes',
    'settings.subtitle': 'Gestiona las preferencias de tu cuenta',
    'settings.languageTitle': 'Language / Idioma',
    'settings.languageDesc': 'Elige tu idioma preferido para la interfaz',
    'settings.languageEn': 'English',
    'settings.languageEs': 'Español',
    'settings.switchToEs': 'Switch to Spanish / Cambiar a Español',
    'settings.switchToEn': 'Cambiar a Inglés / Switch to English',
    'settings.appearanceTitle': 'Apariencia',
    'settings.appearanceDesc': 'Elige entre modo claro y oscuro',
    'settings.darkMode': 'Modo oscuro',
    'settings.lightMode': 'Modo claro',
    'settings.themeToggleDesc': 'Alternar entre apariencia clara y oscura',
    'settings.notificationsTitle': 'Notificaciones',
    'settings.notificationsDesc': 'Gestiona cómo recibes actualizaciones y alertas',
    'settings.emailNotifications': 'Notificaciones por correo',
    'settings.emailNotificationsDesc': 'Recibe actualizaciones sobre el rendimiento de tu página',
    'settings.weeklyDigest': 'Resumen semanal',
    'settings.weeklyDigestDesc': 'Recibe un resumen de tus analíticas cada semana',

    // Dashboard Page
    'dash.title': 'Panel',
    'dash.welcome': 'Bienvenido a tu panel de TitiLinks',
    'dash.last7days': 'Últimos 7 días',
    'dash.allTime': 'Todo el tiempo',
    'dash.totalViews': 'Vistas totales',
    'dash.linkClicks': 'Clics en enlaces',
    'dash.clickRate': 'Tasa de clics',
    'dash.activeLinks': 'Enlaces activos',
    'dash.periodLast7': 'últimos 7 días',
    'dash.periodLast30': 'últimos 30 días',
    'dash.quickStart': 'Inicio rápido',
    'dash.quickStartDesc': 'Comienza configurando tu perfil en la pestaña de Configuración, luego agrega tus enlaces en el Editor.',

    // Dashboard Layout
    'dashLayout.dashboard': 'Panel',
    'dashLayout.editor': 'Editor',
    'dashLayout.design': 'Personalizar Perfil',
    'dashLayout.analytics': 'Analíticas',
    'dashLayout.settings': 'Ajustes',
    'dashLayout.profileSetup': 'Configurar perfil',
    'dashLayout.signOut': 'Cerrar sesión',
    'dashLayout.profileCompletion': 'Perfil completado',
    'dashLayout.completeProfile': 'Completa tu perfil →',
    'dashLayout.displayName': 'Nombre para mostrar',
    'dashLayout.bio': 'Biografía',
    'dashLayout.profilePhoto': 'Foto de perfil',
    'dashLayout.customHandle': 'Handle personalizado',
    'dashLayout.addContentBlocks': 'Agregar bloques de contenido',
    'dashLayout.upgradePlan': 'Mejora tu plan',
    'dashLayout.unlockFeatures': 'Desbloquea más funciones y haz crecer tu audiencia más rápido.',
    'dashLayout.unlockFeaturesMobile': 'Desbloquea más funciones y crece más rápido.',
    'dashLayout.viewPlans': 'Ver planes',
    'dashLayout.unlimitedLinks': 'Enlaces ilimitados',
    'dashLayout.customThemes': 'Temas personalizados',
    'dashLayout.advancedAnalytics': 'Analíticas avanzadas',
    'dashLayout.prioritySupport': 'Soporte prioritario',
    'dashLayout.everythingInPro': 'Todo en Pro',
    'dashLayout.customDomain': 'Dominio personalizado',
    'dashLayout.removeBranding': 'Eliminar marca',
    'dashLayout.apiAccess': 'Acceso API',

    // Login / Auth
    'login.backToHome': 'Volver al inicio',
    'login.welcomeBack': 'Bienvenido de nuevo',
    'login.createAccount': 'Crear cuenta',
    'login.resetPassword': 'Restablecer contraseña',
    'login.signInSubtitle': 'Inicia sesión para gestionar tus enlaces',
    'login.signUpSubtitle': 'Regístrate para crear tu página TitiLinks',
    'login.resetSubtitle': 'Ingresa tu email para recibir un enlace de restablecimiento',
    'login.emailLabel': 'Correo electrónico',
    'login.passwordLabel': 'Contraseña',
    'login.emailPlaceholder': 'tu@ejemplo.com',
    'login.passwordPlaceholder': '••••••••',
    'login.signIn': 'Iniciar sesión',
    'login.signUp': 'Regístrate',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.sendResetLink': 'Enviar enlace',
    'login.backToSignIn': 'Volver a iniciar sesión',
    'login.orContinueWith': 'O continuar con',
    'login.continueWithGoogle': 'Continuar con Google',
    'login.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'login.dontHaveAccount': '¿No tienes una cuenta?',
    'login.checkYourEmail': 'Revisa tu correo',
    'login.confirmationSent': 'Hemos enviado un enlace de confirmación a',
    'login.clickToActivate': 'Haz clic en el enlace para activar tu cuenta.',
    'login.didntReceive': '¿No lo recibiste? Revisa tu carpeta de spam o intenta de nuevo.',
    'login.resendConfirmation': 'Reenviar correo de confirmación',
    'login.resetSent': 'Hemos enviado un enlace de restablecimiento a',
    'login.validationEmail': 'Por favor ingresa un correo válido',
    'login.validationPassword': 'La contraseña debe tener al menos 6 caracteres',
    'login.errorAlreadyRegistered': 'Este correo ya está registrado. Intenta iniciar sesión.',
    'login.errorInvalidCredentials': 'Correo o contraseña inválidos. Intenta de nuevo.',
    'login.newHereCta': '¿Eres nuevo? Crea una cuenta →',
    'login.errorGoogleFailed': 'Error al iniciar sesión con Google',

    // Onboarding Form
    'onboarding.createYourPage': 'Crea tu página',
    'onboarding.stepOf': 'Paso',
    'onboarding.of': 'de',
    'onboarding.profileDetails': 'Detalles del perfil',
    'onboarding.themeAppearance': 'Tema y apariencia',
    'onboarding.uploadAvatar': 'Subir avatar',
    'onboarding.avatarSizeLimit': 'Máx 2MB, JPEG/PNG/GIF/WebP',
    'onboarding.displayName': 'Nombre para mostrar',
    'onboarding.displayNamePlaceholder': 'Tu nombre',
    'onboarding.handle': 'Handle',
    'onboarding.handlePlaceholder': 'tuhandle',
    'onboarding.bioOptional': 'Bio (opcional)',
    'onboarding.bioPlaceholder': 'Cuéntale a la gente sobre ti...',
    'onboarding.continue': 'Continuar',
    'onboarding.themeMode': 'Modo del tema',
    'onboarding.light': 'Claro',
    'onboarding.dark': 'Oscuro',
    'onboarding.accentColor': 'Color de acento',
    'onboarding.preview': 'Vista previa',
    'onboarding.back': 'Volver',
    'onboarding.createPage': 'Crear página',
    'onboarding.creating': 'Creando...',
    'onboarding.pageCreated': '¡Tu página ha sido creada!',
    'onboarding.pageCreatedTitle': '¡Página creada!',
    'onboarding.redirecting': 'Redirigiendo a tu editor…',
    'onboarding.handleTaken': 'Este handle ya está en uso',
    'onboarding.handleTakenToast': 'Este handle ya está en uso. Por favor elige otro.',
    'onboarding.avatarTooLarge': 'El avatar debe ser menor a 2MB',
    'onboarding.avatarInvalidType': 'Solo se permiten imágenes JPEG, PNG, GIF y WebP',
    'onboarding.failedToCreatePage': 'Error al crear la página',

    // Block Editor Dialog
    'blockEditor.failedToLoad': 'Error al cargar bloque',
    'blockEditor.unknownType': 'Tipo de bloque desconocido',

    // Block Item
    'blockItem.primaryCta': 'CTA Principal',
    'blockItem.productCards': 'Tarjetas de producto',
    'blockItem.featuredMedia': 'Medios destacados',
    'blockItem.socialLinks': 'Redes sociales',
    'blockItem.links': 'Enlaces',

    // Not Found Page
    'notFound.title': '¡Ups! Página no encontrada',
    'notFound.returnHome': 'Volver al inicio',

    // Setup Page
    'setup.heading': '¿Cómo te gustaría configurar tu página?',
    'setup.recommended': 'Recomendado',
    'setup.aiTitle': 'Inicio rápido con IA',
    'setup.aiDesc': 'Responde algunas preguntas y construiremos tu página automáticamente — enlaces, bios y todo.',
    'setup.aiFeature1': 'Bios generadas por IA',
    'setup.aiFeature2': 'Bloques de enlaces prediseñados',
    'setup.aiFeature3': 'Listo en 2 minutos',
    'setup.aiButton': 'Comenzar con IA',
    'setup.manualTitle': 'Hacerlo yo mismo',
    'setup.manualDesc': 'Configura tu perfil y agrega tus propios enlaces paso a paso. Sugerencias de IA también disponibles.',
    'setup.manualFeature1': 'Control creativo total',
    'setup.manualFeature2': 'Sugerencias de texto con IA',
    'setup.manualFeature3': 'Construye a tu ritmo',
    'setup.manualButton': 'Configuración manual',

    // Short Link Redirect
    'shortLink.notFound': 'Enlace no encontrado',
    'shortLink.error': 'Error',
    'shortLink.failedResolve': 'Error al resolver enlace',
    'shortLink.somethingWrong': 'Algo salió mal',
    'shortLink.redirecting': 'Redirigiendo...',

    // Suggest Links Dialog
    'suggestLinks.title': 'Sugerir enlaces',
    'suggestLinks.description': 'Describe lo que quieres promocionar y la IA sugerirá enlaces para tu página.',
    'suggestLinks.placeholder': 'ej. Mi nuevo programa de fitness y línea de suplementos',
    'suggestLinks.thinking': 'Pensando...',
    'suggestLinks.suggest': 'Sugerir',
    'suggestLinks.selected': 'seleccionados',
    'suggestLinks.deselectAll': 'Deseleccionar todo',
    'suggestLinks.selectAll': 'Seleccionar todo',
    'suggestLinks.cancel': 'Cancelar',
    'suggestLinks.addSelected': 'Agregar seleccionados',
    'suggestLinks.describePrompt': 'Describe lo que quieres promocionar',
    'suggestLinks.unexpectedFormat': 'Formato de respuesta inesperado',
    'suggestLinks.failedGenerate': 'Error al generar sugerencias',
    'suggestLinks.selectAtLeastOne': 'Selecciona al menos un enlace',
    'suggestLinks.addedLinks': 'Agregados',
    'suggestLinks.link': 'enlace',
    'suggestLinks.links': 'enlaces',
    'suggestLinks.failedAdd': 'Error al agregar enlaces',

    // Templates Page
    'templates.title': 'Encuentra tu',
    'templates.title2': 'plantilla perfecta',
    'templates.subtitle': 'Explora plantillas diseñadas para tu industria y comienza a personalizar en segundos.',
    'templates.comingSoon': '¡Haz clic en cualquier categoría para explorar plantillas próximamente!',
    'templates.backToCategories': 'Volver a categorías',
    'templates.categoryTitle': 'Plantillas',
    'templates.categorySubtitle': 'Elige una plantilla que se adapte a tu estilo y comienza a construir tu página en minutos.',
    'templates.preview': 'Vista previa',
    'templates.useTemplate': 'Usar Esta Plantilla',
    'templates.noTemplates': 'Aún no hay plantillas disponibles para esta categoría.',
    'templates.category.fashion': 'Moda',
    'templates.category.healthFitness': 'Salud y Fitness',
    'templates.category.influencer': 'Influencer y Creador',
    'templates.category.marketing': 'Marketing',
    'templates.category.music': 'Música',
    'templates.category.smallBusiness': 'Pequeños Negocios',
    'templates.category.socialMedia': 'Redes Sociales',
    'templates.category.sports': 'Deportes',
    'templates.category.telegram': 'Telegram',
    'templates.category.whatsapp': 'Whatsapp',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function detectBrowserLanguage(): Language {
  const browserLang = navigator.language.split('-')[0];
  return browserLang === 'es' ? 'es' : 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('titilinks-language');
    if (saved === 'en' || saved === 'es') return saved;
    return detectBrowserLanguage();
  });

  useEffect(() => {
    localStorage.setItem('titilinks-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    console.log('[useLanguage] switching language:', language, '→', lang);
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const value = translations[language][key];
    if (!value) {
      console.warn('[useLanguage] missing key:', key, 'for language:', language);
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
